# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 22:45
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericOnetimeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'USD', max_digits=20)),
                ('date', models.DateField()),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventures.Venture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericOnetimeIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'USD', max_digits=20)),
                ('date', models.DateField()),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventures.Venture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericRecurringExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'USD', max_digits=20)),
                ('date', models.DateField()),
                ('frequency', models.CharField(choices=[(b'hourly', b'hourly'), (b'daily', b'daily'), (b'weekdays', b'weekdays'), (b'weekends', b'weekends'), (b'weekly', b'weekly'), (b'biweekly', b'biweekly'), (b'monthly', b'monthly'), (b'yearly', b'yearly')], max_length=15)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventures.Venture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericRecurringIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency=b'USD', max_digits=20)),
                ('date', models.DateField()),
                ('frequency', models.CharField(choices=[(b'hourly', b'hourly'), (b'daily', b'daily'), (b'weekdays', b'weekdays'), (b'weekends', b'weekends'), (b'weekly', b'weekly'), (b'biweekly', b'biweekly'), (b'monthly', b'monthly'), (b'yearly', b'yearly')], max_length=15)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventures.Venture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
